inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Naming/VariableName:
  EnforcedStyle: snake_case

Naming/AsciiIdentifiers:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

# allow to describe comments with Japanese
Style/AsciiComments:
  Enabled: false

Layout/LineLength:
  Max: 120
  AllowHeredoc: enabled
  AllowURI: enabled

Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block

Layout/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: space

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

# temporarily disabled cops

Style/RedundantArgument:
  Enabled: false

Style/UnlessElse:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false
