# vim:    foldmethod=marker foldlevel=0 foldcolumn=1
# source: https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000188411_00037.html
labels:
  - { index: 57,  code: 190117710, label: 急一般１        } # Ａ100 一般病棟入院基本料（急性期一般入院基本料の急性期一般入院料1）を算定した場合
  - { index: 58,  code: 190199710, label: 急一般２        } # Ａ100 一般病棟入院基本料（急性期一般入院基本料の急性期一般入院料2）を算定した場合
  - { index: 59,  code: 190199810, label: 急一般３        } # Ａ100 一般病棟入院基本料（急性期一般入院基本料の急性期一般入院料3）を算定した場合
  - { index: 60,  code: 190199910, label: 急一般４        } # Ａ100 一般病棟入院基本料（急性期一般入院基本料の急性期一般入院料4）を算定した場合
  - { index: 61,  code: 190200010, label: 急一般５        } # Ａ100 一般病棟入院基本料（急性期一般入院基本料の急性期一般入院料5）を算定した場合
  - { index: 62,  code: 190077410, label: 急一般６        } # Ａ100 一般病棟入院基本料（急性期一般入院基本料の急性期一般入院料6）を算定した場合
  - { index: 63,  code: 190200210, label: 地一般１        } # Ａ100 一般病棟入院基本料（地域一般入院基本料の地域一般入院料1）を算定した場合
  - { index: 64,  code: 190077510, label: 地一般２        } # Ａ100 一般病棟入院基本料（地域一般入院基本料の地域一般入院料2）を算定した場合
  - { index: 65,  code: 190077610, label: 地一般３        } # Ａ100 一般病棟入院基本料（地域一般入院基本料の地域一般入院料3）を算定した場合
  - { index: 66,  code: 190079010, label: 一般特別        } # Ａ100 一般病棟入院基本料の特別入院基本料等を算定した場合

  # 療養病棟
  - { index: 78,  code: 190121310, label: 療１Ａ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ａ）を算定した場合
  - { index: 79,  code: 190121410, label: 療１Ｂ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｂ）を算定した場合
  - { index: 80,  code: 190121510, label: 療１Ｃ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｃ）を算定した場合
  - { index: 81,  code: 190121610, label: 療１Ｄ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｄ）を算定した場合
  - { index: 82,  code: 190121710, label: 療１Ｅ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｅ）を算定した場合
  - { index: 83,  code: 190131610, label: 療１Ｆ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｆ）を算定した場合
  - { index: 84,  code: 190131810, label: 療１Ｇ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｇ）を算定した場合
  - { index: 85,  code: 190132010, label: 療１Ｈ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｈ）を算定した場合
  - { index: 86,  code: 190132210, label: 療１Ｉ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｉ）を算定した場合
  # 療養病棟(生活療養)
  - { index: 78,  code: 190123710, label: 療１Ａ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ａ）を算定した場合
  - { index: 79,  code: 190123810, label: 療１Ｂ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｂ）を算定した場合
  - { index: 80,  code: 190123910, label: 療１Ｃ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｃ）を算定した場合
  - { index: 81,  code: 190124010, label: 療１Ｄ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｄ）を算定した場合
  - { index: 82,  code: 190124110, label: 療１Ｅ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｅ）を算定した場合
  - { index: 83,  code: 190131710, label: 療１Ｆ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｆ）を算定した場合
  - { index: 84,  code: 190131910, label: 療１Ｇ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｇ）を算定した場合
  - { index: 85,  code: 190132110, label: 療１Ｈ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｈ）を算定した場合
  - { index: 86,  code: 190132310, label: 療１Ｉ          } # Ａ101 療養病棟入院基本料（療養病棟入院料１の入院料Ｉ）を算定した場合

  # 療養病棟
  - { index: 87,  code: 190132410, label: 療２Ａ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ａ）を算定した場合
  - { index: 88,  code: 190132610, label: 療２Ｂ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｂ）を算定した場合
  - { index: 89,  code: 190132810, label: 療２Ｃ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｃ）を算定した場合
  - { index: 90,  code: 190133010, label: 療２Ｄ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｄ）を算定した場合
  - { index: 91,  code: 190133210, label: 療２Ｅ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｅ）を算定した場合
  - { index: 92,  code: 190133410, label: 療２Ｆ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｆ）を算定した場合
  - { index: 93,  code: 190133610, label: 療２Ｇ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｇ）を算定した場合
  - { index: 94,  code: 190133810, label: 療２Ｈ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｈ）を算定した場合
  - { index: 95,  code: 190134010, label: 療２Ｉ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｉ）を算定した場合
  # 療養病棟(生活療養)
  - { index: 87,  code: 190132510, label: 療２Ａ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ａ）を算定した場合
  - { index: 88,  code: 190132710, label: 療２Ｂ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｂ）を算定した場合
  - { index: 89,  code: 190132910, label: 療２Ｃ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｃ）を算定した場合
  - { index: 90,  code: 190133110, label: 療２Ｄ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｄ）を算定した場合
  - { index: 91,  code: 190133310, label: 療２Ｅ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｅ）を算定した場合
  - { index: 92,  code: 190133510, label: 療２Ｆ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｆ）を算定した場合
  - { index: 93,  code: 190133710, label: 療２Ｇ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｇ）を算定した場合
  - { index: 94,  code: 190133910, label: 療２Ｈ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｈ）を算定した場合
  - { index: 95,  code: 190134110, label: 療２Ｉ          } # Ａ101 療養病棟入院基本料（療養病棟入院料２の入院料Ｉ）を算定した場合

  - { index: 96,  code: 190121810, label: 療特            } # Ａ101 療養病棟入院基本料の特別入院基本料等を算定した場合

  - { index: 217, code: 190172170, label: 録管１          } # Ａ207 診療録管理体制加算１を算定した場合
  - { index: 218, code: 190100370, label: 録管２          } # Ａ207 診療録管理体制加算２を算定した場合

  # 200床以上
  - { index: 327, code: 190149210, label: デ提１          } # Ａ245 データ提出加算１を算定した場合
  - { index: 328, code: 190149410, label: デ提２          } # Ａ245 データ提出加算２を算定した場合
  - { index: 329, code: 190217510, label: デ提３          } # Ａ245 データ提出加算３を算定した場合
  - { index: 330, code: 190217710, label: デ提４          } # Ａ245 データ提出加算４を算定した場合
  # 200床未満
  - { index: 327, code: 190207010, label: デ提１          } # Ａ245 データ提出加算１を算定した場合
  - { index: 328, code: 190207110, label: デ提２          } # Ａ245 データ提出加算２を算定した場合
  - { index: 329, code: 190217610, label: デ提３          } # Ａ245 データ提出加算３を算定した場合
  - { index: 330, code: 190217810, label: デ提４          } # Ａ245 データ提出加算４を算定した場合

  # 一般
  - { index: 332, code: 190192310, label: 入退支１        } # Ａ246 入退院支援加算１を算定した場合
  - { index: 333, code: 190192510, label: 入退支２        } # Ａ246 入退院支援加算２を算定した場合
  # 療養
  - { index: 332, code: 190192410, label: 入退支１        } # Ａ246 入退院支援加算１を算定した場合
  - { index: 333, code: 190192610, label: 入退支２        } # Ａ246 入退院支援加算２を算定した場合
  - { index: 334, code: 190192710, label: 入退支３        } # Ａ246 入退院支援加算３を算定した場合

  - { index: 529, code: 190266010, label: 短手３          }  # 短手３（ＭＳＬＴ）
  - { index: 529, code: 190179810, label: 短手３          }  # 短手３（下肢静脈瘤手術（抜去切除術））
  - { index: 529, code: 190179910, label: 短手３          }  # 短手３（下肢静脈瘤手術（抜去切除術））（生活療養）
  - { index: 529, code: 190180010, label: 短手３          }  # 短手３（下肢静脈瘤手術（硬化療法））
  - { index: 529, code: 190180110, label: 短手３          }  # 短手３（下肢静脈瘤手術（硬化療法））（生活療養）
  - { index: 529, code: 190180210, label: 短手３          }  # 短手３（下肢静脈瘤手術（高位結紮術））
  - { index: 529, code: 190180310, label: 短手３          }  # 短手３（下肢静脈瘤手術（高位結紮術））（生活療養）
  - { index: 529, code: 190271210, label: 短手３          }  # 短手３（下肢静脈瘤血管内塞栓術）
  - { index: 529, code: 190271310, label: 短手３          }  # 短手３（下肢静脈瘤血管内塞栓術）（生活療養）
  - { index: 529, code: 190271010, label: 短手３          }  # 短手３（下肢静脈瘤血管内焼灼術）
  - { index: 529, code: 190271110, label: 短手３          }  # 短手３（下肢静脈瘤血管内焼灼術）（生活療養）
  - { index: 529, code: 190270610, label: 短手３          }  # 短手３（乳腺腫瘍摘出術（長径５ｃｍ以上）
  - { index: 529, code: 190270710, label: 短手３          }  # 短手３（乳腺腫瘍摘出術（長径５ｃｍ以上）（生活療養）
  - { index: 529, code: 190179610, label: 短手３          }  # 短手３（乳腺腫瘍摘出術（長径５ｃｍ未満））
  - { index: 529, code: 190179710, label: 短手３          }  # 短手３（乳腺腫瘍摘出術（長径５ｃｍ未満））（生活療養）
  - { index: 529, code: 190197710, label: 短手３          }  # 短手３（体外衝撃波腎・尿管結石破砕術）
  - { index: 529, code: 190197810, label: 短手３          }  # 短手３（体外衝撃波腎・尿管結石破砕術）（生活療養）
  - { index: 529, code: 190266210, label: 短手３          }  # 短手３（内分泌負荷試験・下垂体前葉負荷試験（ＧＨ））
  - { index: 529, code: 190266310, label: 短手３          }  # 短手３（内分泌負荷試験・下垂体前葉負荷試験（ＧＨ））（生活療養）
  - { index: 529, code: 190181410, label: 短手３          }  # 短手３（内視鏡的大腸ポリープ・粘膜切除術２ｃｍ以上）
  - { index: 529, code: 190181510, label: 短手３          }  # 短手３（内視鏡的大腸ポリープ・粘膜切除術２ｃｍ以上）（生活療養）
  - { index: 529, code: 190181210, label: 短手３          }  # 短手３（内視鏡的大腸ポリープ・粘膜切除術２ｃｍ未満）
  - { index: 529, code: 190181310, label: 短手３          }  # 短手３（内視鏡的大腸ポリープ・粘膜切除術２ｃｍ未満）（生活療養）
  - { index: 529, code: 190178410, label: 短手３          }  # 短手３（前立腺針生検法・その他）
  - { index: 529, code: 190178510, label: 短手３          }  # 短手３（前立腺針生検法・その他）（生活療養）
  - { index: 529, code: 190270410, label: 短手３          }  # 短手３（喉頭・声帯ポリープ切除術（直達喉頭鏡、ファイバー））
  - { index: 529, code: 190270510, label: 短手３          }  # 短手３（喉頭・声帯ポリープ切除術（直達喉頭鏡、ファイバー）生活）
  - { index: 529, code: 190266610, label: 短手３          }  # 短手３（四肢・躯幹軟部腫瘍摘出術（手））
  - { index: 529, code: 190266710, label: 短手３          }  # 短手３（四肢・躯幹軟部腫瘍摘出術（手））（生活療養）
  - { index: 529, code: 190270810, label: 短手３          }  # 短手３（大伏在静脈抜去術）
  - { index: 529, code: 190270910, label: 短手３          }  # 短手３（大伏在静脈抜去術）（生活療養）
  - { index: 529, code: 190272810, label: 短手３          }  # 短手３（子宮鏡下子宮筋腫摘出術（その他））
  - { index: 529, code: 190272910, label: 短手３          }  # 短手３（子宮鏡下子宮筋腫摘出術（その他））（生活療養）
  - { index: 529, code: 190272610, label: 短手３          }  # 短手３（子宮鏡下子宮筋腫摘出術（電解質溶液利用））
  - { index: 529, code: 190272710, label: 短手３          }  # 短手３（子宮鏡下子宮筋腫摘出術（電解質溶液利用））（生活療養）
  - { index: 529, code: 190272410, label: 短手３          }  # 短手３（子宮鏡下有茎粘膜下筋腫切出、ポリープ切除・その他）
  - { index: 529, code: 190272510, label: 短手３          }  # 短手３（子宮鏡下有茎粘膜下筋腫切出、ポリープ切除・その他・生活）
  - { index: 529, code: 190272210, label: 短手３          }  # 短手３（子宮鏡下有茎粘膜下筋腫切出、ポリープ切除・電解液）
  - { index: 529, code: 190272310, label: 短手３          }  # 短手３（子宮鏡下有茎粘膜下筋腫切出、ポリープ切除・電解液・生活）
  - { index: 529, code: 190181810, label: 短手３          }  # 短手３（子宮頸部（腟部）切除術）
  - { index: 529, code: 190181910, label: 短手３          }  # 短手３（子宮頸部（腟部）切除術）（生活療養）
  - { index: 529, code: 190197910, label: 短手３          }  # 短手３（ガンマナイフによる定位放射線治療）
  - { index: 529, code: 190198010, label: 短手３          }  # 短手３（ガンマナイフによる定位放射線治療）（生活療養）
  - { index: 529, code: 190178210, label: 短手３          }  # 短手３（小児食物アレルギー負荷検査）
  - { index: 529, code: 190178310, label: 短手３          }  # 短手３（小児食物アレルギー負荷検査）（生活療養）
  - { index: 529, code: 190271810, label: 短手３          }  # 短手３（尿失禁手術（ボツリヌス毒素によるもの））
  - { index: 529, code: 190271910, label: 短手３          }  # 短手３（尿失禁手術（ボツリヌス毒素によるもの））（生活療養）
  - { index: 529, code: 190267610, label: 短手３          }  # 短手３（ガングリオン摘出術（手））
  - { index: 529, code: 190267710, label: 短手３          }  # 短手３（ガングリオン摘出術（手））（生活療養）
  - { index: 529, code: 190269010, label: 短手３          }  # 短手３（斜視手術（前転法及び後転法の併施））
  - { index: 529, code: 190269110, label: 短手３          }  # 短手３（斜視手術（前転法及び後転法の併施））（生活療養）
  - { index: 529, code: 190268810, label: 短手３          }  # 短手３（斜視手術（後転法））
  - { index: 529, code: 190268910, label: 短手３          }  # 短手３（斜視手術（後転法））（生活療養）
  - { index: 529, code: 190269810, label: 短手３          }  # 短手３（水晶体再建術・眼内レンズを挿入しない・両側）
  - { index: 529, code: 190269910, label: 短手３          }  # 短手３（水晶体再建術・眼内レンズを挿入しない・両側）（生活療養）
  - { index: 529, code: 190195910, label: 短手３          }  # 短手３（水晶体再建術・眼内レンズ挿入・その他・両側）
  - { index: 529, code: 190196010, label: 短手３          }  # 短手３（水晶体再建術・眼内レンズ挿入・その他・両側）（生活療養）
  - { index: 529, code: 190179210, label: 短手３          }  # 短手３（水晶体再建術・眼内レンズ挿入・その他・片側）
  - { index: 529, code: 190179310, label: 短手３          }  # 短手３（水晶体再建術・眼内レンズ挿入・その他・片側）（生活療養）
  - { index: 529, code: 190269610, label: 短手３          }  # 短手３（水晶体再建術・眼内レンズを挿入しない・片側）
  - { index: 529, code: 190269710, label: 短手３          }  # 短手３（水晶体再建術・眼内レンズを挿入しない・片側）（生活療養）
  - { index: 529, code: 190269210, label: 短手３          }  # 短手３（治療的角膜切除術・エキシマレーザー）
  - { index: 529, code: 190269310, label: 短手３          }  # 短手３（治療的角膜切除術・エキシマレーザー）（生活療養）
  - { index: 529, code: 190267810, label: 短手３          }  # 短手３（涙管チューブ挿入術（涙道内視鏡））
  - { index: 529, code: 190267910, label: 短手３          }  # 短手３（涙管チューブ挿入術（涙道内視鏡））（生活療養）
  - { index: 529, code: 190266110, label: 短手３          }  # 短手３（ＭＳＬＴ）（生活療養）
  - { index: 529, code: 190181610, label: 短手３          }  # 短手３（痔核手術（硬化療法（四段階注射法）））
  - { index: 529, code: 190181710, label: 短手３          }  # 短手３（痔核手術（硬化療法（四段階注射法）））（生活療養）
  - { index: 529, code: 190268410, label: 短手３          }  # 短手３（眼瞼下垂症手術（その他のもの））
  - { index: 529, code: 190268510, label: 短手３          }  # 短手３（眼瞼下垂症手術（その他のもの））（生活療養）
  - { index: 529, code: 190268210, label: 短手３          }  # 短手３（眼瞼下垂症手術（眼瞼挙筋前転法））
  - { index: 529, code: 190268310, label: 短手３          }  # 短手３（眼瞼下垂症手術（眼瞼挙筋前転法））（生活療養）
  - { index: 529, code: 190268010, label: 短手３          }  # 短手３（眼瞼内反症手術（皮膚切開法））
  - { index: 529, code: 190268110, label: 短手３          }  # 短手３（眼瞼内反症手術（皮膚切開法））（生活療養）
  - { index: 529, code: 190265710, label: 短手３          }  # 短手３（終夜睡眠ポリグラフィー１、２以外・安全精度管理下・生活）
  - { index: 529, code: 190265810, label: 短手３          }  # 短手３（終夜睡眠ポリグラフィー・１及び２以外・その他）
  - { index: 529, code: 190265910, label: 短手３          }  # 短手３（終夜睡眠ポリグラフィー・１及び２以外・その他・生活療養）
  - { index: 529, code: 190265610, label: 短手３          }  # 短手３（終夜睡眠ポリグラフィー・１及び２以外・安全精度管理下）
  - { index: 529, code: 190220910, label: 短手３          }  # 短手３（経皮的シャント拡張術・血栓除去術（初回））
  - { index: 529, code: 190221010, label: 短手３          }  # 短手３（経皮的シャント拡張術・血栓除去術（初回））（生活療養）
  - { index: 529, code: 190221110, label: 短手３          }  # 短手３（経皮的シャント拡張術・血栓除去術・３月以内）
  - { index: 529, code: 190221210, label: 短手３          }  # 短手３（経皮的シャント拡張術・血栓除去術・３月以内）（生活療養）
  - { index: 529, code: 190266410, label: 短手３          }  # 短手３（経皮的放射線治療用金属マーカー留置術）
  - { index: 529, code: 190266510, label: 短手３          }  # 短手３（経皮的放射線治療用金属マーカー留置術）（生活療養）
  - { index: 529, code: 190269410, label: 短手３          }  # 短手３（緑内障手術・水晶体再建術併用眼内ドレーン挿入術）
  - { index: 529, code: 190269510, label: 短手３          }  # 短手３（緑内障手術・水晶体再建術併用眼内ドレーン挿入術・生活）
  - { index: 529, code: 190268610, label: 短手３          }  # 短手３（翼状片手術（弁の移植を要するもの））
  - { index: 529, code: 190268710, label: 短手３          }  # 短手３（翼状片手術（弁の移植を要するもの））（生活療養）
  - { index: 529, code: 190271410, label: 短手３          }  # 短手３（肛門ポリープ切除術）
  - { index: 529, code: 190271510, label: 短手３          }  # 短手３（肛門ポリープ切除術）（生活療養）
  - { index: 529, code: 190271610, label: 短手３          }  # 短手３（肛門尖圭コンジローム切除術）
  - { index: 529, code: 190271710, label: 短手３          }  # 短手３（肛門尖圭コンジローム切除術）（生活療養）
  - { index: 529, code: 190179010, label: 短手３          }  # 短手３（胸腔鏡下交感神経節切除術（両側））
  - { index: 529, code: 190179110, label: 短手３          }  # 短手３（胸腔鏡下交感神経節切除術（両側））（生活療養）
  - { index: 529, code: 190273010, label: 短手３          }  # 短手３（腹腔鏡下卵管形成術）
  - { index: 529, code: 190273110, label: 短手３          }  # 短手３（腹腔鏡下卵管形成術）（生活療養）
  - { index: 529, code: 190181010, label: 短手３          }  # 短手３（腹腔鏡下鼠径ヘルニア手術（１５歳以上））
  - { index: 529, code: 190197310, label: 短手３          }  # 短手３（腹腔鏡下鼠径ヘルニア手術（６歳以上１５歳未満））
  - { index: 529, code: 190197210, label: 短手３          }  # 短手３（腹腔鏡下鼠径ヘルニア手術（３歳以上６歳未満））
  - { index: 529, code: 190197610, label: 短手３          }  # 短手３（腹腔鏡下鼠径ヘルニア手術（６歳以上１５歳未満））生活療養
  - { index: 529, code: 190197510, label: 短手３          }  # 短手３（腹腔鏡下鼠径ヘルニア手術（３歳以上６歳未満））生活療養
  - { index: 529, code: 190197610, label: 短手３          }  # 短手３（腹腔鏡下鼠径ヘルニア手術（６歳以上１５歳未満））生活療養
  - { index: 529, code: 190197510, label: 短手３          }  # 短手３（腹腔鏡下鼠径ヘルニア手術（３歳以上６歳未満））生活療養
  - { index: 529, code: 190181110, label: 短手３          }  # 短手３（腹腔鏡下鼠径ヘルニア手術（１５歳以上））（生活療養）
  - { index: 529, code: 190197110, label: 短手３          }  # 短手３（腹腔鏡下鼠径ヘルニア手術（３歳未満））
  - { index: 529, code: 190197410, label: 短手３          }  # 短手３（腹腔鏡下鼠径ヘルニア手術（３歳未満））（生活療養）
  - { index: 529, code: 190178810, label: 短手３          }  # 短手３（関節鏡下手根管開放手術）
  - { index: 529, code: 190178910, label: 短手３          }  # 短手３（関節鏡下手根管開放手術）（生活療養）
  - { index: 529, code: 190272010, label: 短手３          }  # 短手３（顕微鏡下精索静脈瘤手術）
  - { index: 529, code: 190272110, label: 短手３          }  # 短手３（顕微鏡下精索静脈瘤手術）（生活療養）
  - { index: 529, code: 190267010, label: 短手３          }  # 短手３（骨内異物（挿入物を含む）除去術（前腕））
  - { index: 529, code: 190267110, label: 短手３          }  # 短手３（骨内異物（挿入物を含む）除去術（前腕））（生活療養）
  - { index: 529, code: 190267410, label: 短手３          }  # 短手３（骨内異物（挿入物を含む）除去術（手））
  - { index: 529, code: 190267510, label: 短手３          }  # 短手３（骨内異物（挿入物を含む）除去術（手））（生活療養）
  - { index: 529, code: 190267210, label: 短手３          }  # 短手３（骨内異物（挿入物を含む）除去術（鎖骨））
  - { index: 529, code: 190267310, label: 短手３          }  # 短手３（骨内異物（挿入物を含む）除去術（鎖骨））（生活療養）
  - { index: 529, code: 190266810, label: 短手３          }  # 短手３（骨折観血的手術（手舟状骨））
  - { index: 529, code: 190266910, label: 短手３          }  # 短手３（骨折観血的手術（手舟状骨））（生活療養）
  - { index: 529, code: 190270010, label: 短手３          }  # 短手３（鼓膜形成手術）
  - { index: 529, code: 190270110, label: 短手３          }  # 短手３（鼓膜形成手術）（生活療養）
  - { index: 529, code: 190180610, label: 短手３          }  # 短手３（鼠径ヘルニア手術（１５歳以上））
  - { index: 529, code: 190196710, label: 短手３          }  # 短手３（鼠径ヘルニア手術（６歳以上１５歳未満））
  - { index: 529, code: 190196610, label: 短手３          }  # 短手３（鼠径ヘルニア手術（３歳以上６歳未満））
  - { index: 529, code: 190197010, label: 短手３          }  # 短手３（鼠径ヘルニア手術（６歳以上１５歳未満））（生活療養）
  - { index: 529, code: 190196910, label: 短手３          }  # 短手３（鼠径ヘルニア手術（３歳以上６歳未満））（生活療養）
  - { index: 529, code: 190180710, label: 短手３          }  # 短手３（鼠径ヘルニア手術（１５歳以上）（生活療養）
  - { index: 529, code: 190196510, label: 短手３          }  # 短手３（鼠径ヘルニア手術（３歳未満））
  - { index: 529, code: 190196810, label: 短手３          }  # 短手３（鼠径ヘルニア手術（３歳未満））（生活療養）
  - { index: 529, code: 190270210, label: 短手３          }  # 短手３（鼻骨骨折整復固定術）
  - { index: 529, code: 190270310, label: 短手３          }  # 短手３（鼻骨骨折整復固定術）（生活療養）
