tags:
  # 点数欄 - 97食事・生活

  # 食事・基準
  - name: shokuji-ryouyou-kijun
    label: ~
    shinryou_shikibetsu: ['97']
    code:
      - 197000110 # 入院時食事療養（１）（１食につき）（２以外の食事療養）
      - 197003110 # 入院時食事療養（１）（１食につき）（流動食のみを提供）
      - 197000710 # 入院時食事療養（２）（１食につき）（２以外の食事療養）
      - 197003210 # 入院時食事療養（２）（１食につき）（流動食のみを提供）
  # 食事・特別
  - name: shokuji-ryouyou-tokubetsu
    label: ~
    shinryou_shikibetsu: ['97']
    code:
      - 197000470 # 特別食加算（食事療養）
      - 197001570 # 特別食加算（生活療養）
  # 食事・食堂
  - name: shokuji-ryouyou-shokudou
    label: ~
    shinryou_shikibetsu: ['97']
    code:
      - 197000570 # 食堂加算（食事療養）
  # 食事・環境
  - name: seikatsu-ryouyou-kankyou
    label: ~
    shinryou_shikibetsu: ['97']
    code:
      - 197001410 # 入院時生活療養（１）環境療養
      - 197001810 # 入院時生活療養（２）環境療養
  # 基準(生)
  - name: seikatsu-ryouyou-kijun
    label: ~
    shinryou_shikibetsu: ['97']
    code:
      - 197001310 # 入院時生活療養（１）食事療養（ロ以外の食事の提供たる療養）
      - 197001710 # 入院時生活療養（２）食事療養
      - 197003510 # 入院時生活療養（１）食事療養（流動食のみを提供）
  # 特別(生)
  - name: seikatsu-ryouyou-tokubetsu
    label: ~
    shinryou_shikibetsu: ['97']
    code:
      - 197001670 # 食堂加算（生活療養）

  # 食事療養費 ローマ数字
  #
  # (22) 「食事・生活」欄について
  #
  # ア 「基準」の項には、入院時食事療養費に係る食事療養について算定した項目について次の略号を用いて記載すること。ただし、複数の食事療養を算定し、「基準」の項に複数の略号を記載することが困難な場合は、「摘要」欄への記載でも差し支えないこと。
  # Ⅰ（入院時食事療養Ⅰ(1)）、Ⅱ（入院時食事療養Ⅱ(1)）、Ⅲ（入院時食事療養Ⅰ(2)）、Ⅳ（入院時食事療養Ⅱ(2)）

  - name: shokuji-kijun-category-i
    label: Ⅰ
    shinryou_shikibetsu: ['97']
    code:
      - 197003110 # 入院時食事療養（１）（１食につき）（流動食のみを提供）
  - name: shokuji-kijun-category-ii
    label: Ⅱ
    shinryou_shikibetsu: ['97']
    code:
      - 197000710 # 入院時食事療養（２）（１食につき）（２以外の食事療養）
  - name: shokuji-kijun-category-iii
    label: Ⅲ
    shinryou_shikibetsu: ['97']
    code:
      - 197003110 # 入院時食事療養（１）（１食につき）（流動食のみを提供）
  - name: shokuji-kijun-category-iv
    label: Ⅳ
    shinryou_shikibetsu: ['97']
    code:
      - 197003210 # 入院時食事療養（２）（１食につき）（流動食のみを提供）

  # 生活療養費 ローマ数字
  #
  # (22) 「食事・生活」欄について
  #
  # オ 「基準（生）」の項には、入院時生活療養費に係る生活療養について算定した項目を次の略号を用いて記載すること。ただし、複数の生活療養を算定し、「基準（生）」の項に複数の略号を記載することが困難な場合は、「摘要」欄への記載でも差し支えないこと。
  # Ⅰ（入院時生活療養Ⅰ(1)イ）、Ⅱ（入院時生活療養Ⅱ）、Ⅲ（入院時生活療養Ⅰ(1)ロ）

  - name: seikatsu-kijun-category-i
    label: Ⅰ
    shinryou_shikibetsu: ['97']
    code:
      - 197001310 # 入院時生活療養（１）食事療養（ロ以外の食事の提供たる療養）
  - name: seikatsu-kijun-category-ii
    label: Ⅱ
    shinryou_shikibetsu: ['97']
    code:
      - 197001710 # 入院時生活療養（２）食事療養
  - name: seikatsu-kijun-category-iii
    label: Ⅲ
    shinryou_shikibetsu: ['97']
    code:
      - 197003510 # 入院時生活療養（１）食事療養（流動食のみを提供）

  # 病床区分
  #
  # 現状では療養病床のみ対応(回復期リハ病棟の療養病床も未対応)

  - name: byoushou-type-ryouyou # 「告示等識別区分（２）」が `1` かつ「コード表用番号（アルファベット部を除く）区分番号」が `101`
    label: 03療養
    shinryou_shikibetsu: ['90']
    code:
      - 190121810 # 療養病棟入院基本料（特別入院基本料）
      - 190124210 # 療養病棟入院基本料（特別入院基本料）（生活療養）
      - 190121310 # 療養病棟入院料１（入院料Ａ）
      - 190121410 # 療養病棟入院料１（入院料Ｂ）
      - 190121510 # 療養病棟入院料１（入院料Ｃ）
      - 190121610 # 療養病棟入院料１（入院料Ｄ）
      - 190121710 # 療養病棟入院料１（入院料Ｅ）
      - 190131610 # 療養病棟入院料１（入院料Ｆ）
      - 190131810 # 療養病棟入院料１（入院料Ｇ）
      - 190132010 # 療養病棟入院料１（入院料Ｈ）
      - 190132210 # 療養病棟入院料１（入院料Ｉ）
      - 190132410 # 療養病棟入院料２（入院料Ａ）
      - 190132610 # 療養病棟入院料２（入院料Ｂ）
      - 190132810 # 療養病棟入院料２（入院料Ｃ）
      - 190133010 # 療養病棟入院料２（入院料Ｄ）
      - 190133210 # 療養病棟入院料２（入院料Ｅ）
      - 190133410 # 療養病棟入院料２（入院料Ｆ）
      - 190133610 # 療養病棟入院料２（入院料Ｇ）
      - 190133810 # 療養病棟入院料２（入院料Ｈ）
      - 190134010 # 療養病棟入院料２（入院料Ｉ）
      - 190123710 # 療養病棟入院料１（入院料Ａ）（生活療養）
      - 190123810 # 療養病棟入院料１（入院料Ｂ）（生活療養）
      - 190123910 # 療養病棟入院料１（入院料Ｃ）（生活療養）
      - 190124010 # 療養病棟入院料１（入院料Ｄ）（生活療養）
      - 190124110 # 療養病棟入院料１（入院料Ｅ）（生活療養）
      - 190131710 # 療養病棟入院料１（入院料Ｆ）（生活療養）
      - 190131910 # 療養病棟入院料１（入院料Ｇ）（生活療養）
      - 190132110 # 療養病棟入院料１（入院料Ｈ）（生活療養）
      - 190132310 # 療養病棟入院料１（入院料Ｉ）（生活療養）
      - 190132510 # 療養病棟入院料２（入院料Ａ）（生活療養）
      - 190132710 # 療養病棟入院料２（入院料Ｂ）（生活療養）
      - 190132910 # 療養病棟入院料２（入院料Ｃ）（生活療養）
      - 190133110 # 療養病棟入院料２（入院料Ｄ）（生活療養）
      - 190133310 # 療養病棟入院料２（入院料Ｅ）（生活療養）
      - 190133510 # 療養病棟入院料２（入院料Ｆ）（生活療養）
      - 190133710 # 療養病棟入院料２（入院料Ｇ）（生活療養）
      - 190133910 # 療養病棟入院料２（入院料Ｈ）（生活療養）
      - 190134110 # 療養病棟入院料２（入院料Ｉ）（生活療養）
      - 190215210 # 療養病棟入院料２（Ａ）（生活療養）（経過措置）
      - 190215410 # 療養病棟入院料２（Ｂ）（生活療養）（経過措置）
      - 190215610 # 療養病棟入院料２（Ｃ）（生活療養）（経過措置）
      - 190215810 # 療養病棟入院料２（Ｄ）（生活療養）（経過措置）
      - 190216010 # 療養病棟入院料２（Ｅ）（生活療養）（経過措置）
      - 190216210 # 療養病棟入院料２（Ｆ）（生活療養）（経過措置）
      - 190216410 # 療養病棟入院料２（Ｇ）（生活療養）（経過措置）
      - 190216610 # 療養病棟入院料２（Ｈ）（生活療養）（経過措置）
      - 190216810 # 療養病棟入院料２（Ｉ）（生活療養）（経過措置）
      - 190215110 # 療養病棟入院料２（Ａ）（経過措置）
      - 190215310 # 療養病棟入院料２（Ｂ）（経過措置）
      - 190215510 # 療養病棟入院料２（Ｃ）（経過措置）
      - 190215710 # 療養病棟入院料２（Ｄ）（経過措置）
      - 190215910 # 療養病棟入院料２（Ｅ）（経過措置）
      - 190216110 # 療養病棟入院料２（Ｆ）（経過措置）
      - 190216310 # 療養病棟入院料２（Ｇ）（経過措置）
      - 190216510 # 療養病棟入院料２（Ｈ）（経過措置）
      - 190216710 # 療養病棟入院料２（Ｉ）（経過措置）
      - 190202410 # 療養病棟・地域一般入院料１
      - 190198310 # 療養病棟・地域一般入院料２
      - 190198410 # 療養病棟・地域一般入院料３
      - 190198110 # 療養病棟・急性期一般入院料１
      - 190201910 # 療養病棟・急性期一般入院料２
      - 190202010 # 療養病棟・急性期一般入院料３
      - 190202110 # 療養病棟・急性期一般入院料４
      - 190202210 # 療養病棟・急性期一般入院料５
      - 190198210 # 療養病棟・急性期一般入院料６
      - 190202310 # 療養病棟・急性期一般入院料６
      - 190198210 # 療養病棟・急性期一般入院料７
      - 190202310 # 療養病棟・急性期一般入院料６（経過措置）
