tags:
  # 点数欄 - 12再診

  # 再診
  - key: tensuu-shuukei-12-saishin
    label: ~
    shinryou_shikibetsu: ['12']
    code:
      - 112007410 # 再診料
      - 112007950 # 電話等再診料
      - 112008350 # 同日再診料
      - 112008850 # 同日電話等再診料
      - 112011310 # 外来診療料
      - 112011710 # 同日外来診療料
      - 112015810 # 再診料（同一日複数科受診時の２科目）
      - 112015950 # 電話等再診料（同一日複数科受診時の２科目）
      - 112016210 # 外来診療料（同一日複数科受診時の２科目）
      - 112016210 # 外来診療料（同一日複数科受診時の２科目）
      - 112016310 # 外来診療料（他医療機関へ文書紹介の申出を行っている患者）
      - 112016310 # 外来診療料（文書紹介申出患者）
      - 112016410 # 外来診療料（同一日複数科受診時の２科目・文書紹介申出患者）
      - 112016410 # 外来診療料（同日複数科２科目・文書紹介申出患者）
      - 112016550 # 同日外来診療料（他医療機関へ文書紹介の申出を行っている患者）
      - 112016550 # 同日外来診療料（文書紹介申出患者）
      - 112016610 # 特定妥結率再診料
      - 112016750 # 電話等特定妥結率再診料
      - 112016850 # 同日特定妥結率再診料
      - 112016950 # 同日電話等特定妥結率再診料
      - 112017010 # 特定妥結率再診料（同一日複数科受診時の２科目）
      - 112017150 # 電話等特定妥結率再診料（同一日複数科受診時の２科目）
      - 112017310 # 特定妥結率外来診療料
      - 112017310 # 特定妥結率外来診療料
      - 112017450 # 同日特定妥結率外来診療料
      - 112017450 # 同日特定妥結率外来診療料
      - 112017610 # 特定妥結率外来診療料（同一日複数科受診時の２科目）
      - 112017610 # 特定妥結率外来診療料（同一日複数科受診時２科目）
      - 112023210 # オンライン診療料
      - 112023350 # 電話等再診料（３０年３月以前継続）
      - 112023450 # 同日電話等再診料（３０年３月以前継続）
      - 112023550 # 電話等再診料（同一日複数科受診時の２科目）（３０年３月以前継続）
      - 112023650 # 電話等特定妥結率再診料（３０年３月以前継続）
      - 112023750 # 同日電話等特定妥結率再診料（３０年３月以前継続）
      - 112023850 # 電話等特定妥結率再診料（同一日複数科２科目・３０年３月以前継続）
      - 112024210 # 再診料（情報通信機器）
      - 112024710 # 外来診療料（情報通信機器）
      - 112024950 # 同日再診料（情報通信機器）
      - 112025010 # 特定妥結率再診料（情報通信機器）
      - 112025150 # 同日特定妥結率再診料（情報通信機器）
      - 112025210 # 再診料（同一日複数科受診時の２科目）（情報通信機器）
      - 112025310 # 特定妥結率再診料（同一日複数科受診時の２科目）（情報通信機器）
      - 112025450 # 同日外来診療料（情報通信機器）
      - 112025510 # 外来診療料（文書紹介申出患者）（情報通信機器）
      - 112025650 # 同日外来診療料（文書紹介申出患者）（情報通信機器）
      - 112025710 # 特定妥結率外来診療料（情報通信機器）
      - 112025850 # 同日特定妥結率外来診療料（情報通信機器）
      - 112025910 # 外来診療料（同一日複数科受診時の２科目）（情報通信機器）
      - 112026010 # 外来診療料（同日複数科２科目・文書紹介申出患者）（情報通信機器）
      - 112026110 # 特定妥結率外来診療料（同一日複数科受診時２科目）（情報通信機器）
      - 112026750 # 電話等再診料（特例）
      - 112026850 # 外来診療料（特例）
  # 外来管理加算
  - key: tensuu-shuukei-12-gairai-kanri
    label: ~
    shinryou_shikibetsu: ['12']
    code:
      - 112011010 # 外来管理加算
  # 時間外
  - key: tensuu-shuukei-12-jikangai
    label: ~
    shinryou_shikibetsu: ['12']
    code:
      - 112001110 # 時間外加算（再診）（入院外）
      - 112001410 # 時間外特例医療機関加算（再診）（入院外）
      - 112006470 # 時間外加算（外来診療料）（入院外）
      - 112006470 # 時間外加算（外来診療料）（入院外）
      - 112006770 # 時間外特例医療機関加算（外来診療料）（入院外）
      - 112006770 # 時間外特例医療機関加算（外来診療料）（入院外）
      - 112014170 # 乳幼児夜間加算（小児科再診）（入院外）
      - 112014470 # 乳幼児夜間加算（小児科・外来診療料）（入院外）
      - 112014470 # 乳幼児夜間加算（小児科・外来診療料）（入院外）
      - 112014770 # 乳幼児時間外加算（再診）（入院外）
      - 112015070 # 乳幼児時間外特例医療機関加算（再診）（入院外）
      - 112015170 # 乳幼児時間外加算（外来診療料）（入院外）
      - 112015170 # 乳幼児時間外加算（外来診療料）（入院外）
      - 112015470 # 乳幼児時間外特例医療機関加算（外来診療料）（入院外）
      - 112015470 # 乳幼児時間外特例医療機関加算（外来診療料）（入院外）
      - 112015570 # 夜間・早朝等加算（再診）
  # 休日
  - key: tensuu-shuukei-12-kyuujitsu
    label: ~
    shinryou_shikibetsu: ['12']
    code:
      - 112001210 # 休日加算（再診）（入院外）
      - 112006570 # 休日加算（外来診療料）（入院外）
      - 112006570 # 休日加算（外来診療料）（入院外）
      - 112014270 # 乳幼児休日加算（小児科再診）（入院外）
      - 112014570 # 乳幼児休日加算（小児科・外来診療料）（入院外）
      - 112014570 # 乳幼児休日加算（小児科・外来診療料）（入院外）
      - 112014870 # 乳幼児休日加算（再診）（入院外）
      - 112015270 # 乳幼児休日加算（外来診療料）（入院外）
      - 112015270 # 乳幼児休日加算（外来診療料）（入院外）
  # 深夜
  - key: tensuu-shuukei-12-shinya
    label: ~
    shinryou_shikibetsu: ['12']
    code:
      - 112001310 # 深夜加算（再診）（入院外）
      - 112006670 # 深夜加算（外来診療料）（入院外）
      - 112006670 # 深夜加算（外来診療料）（入院外）
      - 112014370 # 乳幼児深夜加算（小児科再診）（入院外）
      - 112014670 # 乳幼児深夜加算（小児科・外来診療料）（入院外）
      - 112014670 # 乳幼児深夜加算（小児科・外来診療料）（入院外）
      - 112014970 # 乳幼児深夜加算（再診）（入院外）
      - 112015370 # 乳幼児深夜加算（外来診療料）（入院外）
      - 112015370 # 乳幼児深夜加算（外来診療料）（入院外）

  # 点数欄 - 80その他

  # 処方せん
  - key: tensuu-shuukei-80-shohousen
    label: ~
    shinryou_shikibetsu: ['80']
    code:
      - 120002710 # 処方箋料（７種類以上内服薬）
      - 120002710 # 処方箋料（リフィル以外・７種類以上内服薬）
      - 120002910 # 処方箋料（リフィル以外・その他）
      - 120002910 # 処方箋料（その他）
      - 120003710 # 処方箋料（リフィル以外・向精神薬多剤投与）
      - 120003710 # 処方箋料（向精神薬多剤投与）
      - 120004610 # 処方箋料（リフィル以外・向精神薬長期処方）
      - 120004610 # 処方箋料（向精神薬長期処方）
      - 120004710 # 処方箋料（リフィル処方箋・向精神薬多剤投与）
      - 120004810 # 処方箋料（リフィル処方箋・７種類以上内服薬）
      - 120004910 # 処方箋料（リフィル処方箋・向精神薬長期処方）
      - 120005010 # 処方箋料（リフィル処方箋・その他）
      - 120002470 # 乳幼児加算（処方箋料）
      - 120002470 # 乳幼児加算（処方箋料）
      - 120002570 # 特定疾患処方管理加算１（処方箋料）
      - 120002570 # 特定疾患処方管理加算１（処方箋料）
      - 120003270 # 特定疾患処方管理加算２（処方箋料）
      - 120003270 # 特定疾患処方管理加算２（処方箋料）
      - 120003470 # 抗悪性腫瘍剤処方管理加算（処方箋料）
      - 120003470 # 抗悪性腫瘍剤処方管理加算（処方箋料）
      - 120003570 # 一般名処方加算２（処方箋料）
      - 120003570 # 一般名処方加算２（処方箋料）
      - 120003970 # 処方箋料減算（紹介率が低い大病院３０日以上投薬）
      - 120003970 # 処方箋料減算（紹介率が低い大病院３０日以上投薬）
      - 120004270 # 一般名処方加算１（処方箋料）
      - 120004270 # 一般名処方加算１（処方箋料）
      - 120004570 # 向精神薬調整連携加算（処方箋料）
      - 120004570 # 向精神薬調整連携加算（処方箋料）
      - 120005470 # 一般名処方加算１（処方箋料）（経過措置）
      - 120005570 # 一般名処方加算２（処方箋料）（経過措置）

  # 点数欄 - 97食事・生活

  # 食事・基準
  - key: shokuji-ryouyou-kijun
    label: ~
    shinryou_shikibetsu: ['97']
    code:
      - 197000110 # 入院時食事療養（１）（１食につき）（２以外の食事療養）
      - 197003110 # 入院時食事療養（１）（１食につき）（流動食のみを提供）
      - 197000710 # 入院時食事療養（２）（１食につき）（２以外の食事療養）
      - 197003210 # 入院時食事療養（２）（１食につき）（流動食のみを提供）
  # 食事・特別
  - key: shokuji-ryouyou-tokubetsu
    label: ~
    shinryou_shikibetsu: ['97']
    code:
      - 197000470 # 特別食加算（食事療養）
      - 197001570 # 特別食加算（生活療養）
  # 食事・食堂
  - key: shokuji-ryouyou-shokudou
    label: ~
    shinryou_shikibetsu: ['97']
    code:
      - 197000570 # 食堂加算（食事療養）
  # 食事・環境
  - key: seikatsu-ryouyou-kankyou
    label: ~
    shinryou_shikibetsu: ['97']
    code:
      - 197001410 # 入院時生活療養（１）環境療養
      - 197001810 # 入院時生活療養（２）環境療養
  # 基準(生)
  - key: seikatsu-ryouyou-kijun
    label: ~
    shinryou_shikibetsu: ['97']
    code:
      - 197001310 # 入院時生活療養（１）食事療養（ロ以外の食事の提供たる療養）
      - 197001710 # 入院時生活療養（２）食事療養
      - 197003510 # 入院時生活療養（１）食事療養（流動食のみを提供）
  # 特別(生)
  - key: seikatsu-ryouyou-tokubetsu
    label: ~
    shinryou_shikibetsu: ['97']
    code:
      - 197001670 # 食堂加算（生活療養）

  # 食事療養費 ローマ数字
  #
  # (22) 「食事・生活」欄について
  #
  # ア 「基準」の項には、入院時食事療養費に係る食事療養について算定した項目について次の略号を用いて記載すること。ただし、複数の食事療養を算定し、「基準」の項に複数の略号を記載することが困難な場合は、「摘要」欄への記載でも差し支えないこと。
  # Ⅰ（入院時食事療養Ⅰ(1)）、Ⅱ（入院時食事療養Ⅱ(1)）、Ⅲ（入院時食事療養Ⅰ(2)）、Ⅳ（入院時食事療養Ⅱ(2)）

  - key: shokuji-kijun-category-i
    label: Ⅰ
    shinryou_shikibetsu: ['97']
    code:
      - 197000110 # 入院時食事療養（１）（１食につき）（２以外の食事療養）
  - key: shokuji-kijun-category-ii
    label: Ⅱ
    shinryou_shikibetsu: ['97']
    code:
      - 197000710 # 入院時食事療養（２）（１食につき）（２以外の食事療養）
  - key: shokuji-kijun-category-iii
    label: Ⅲ
    shinryou_shikibetsu: ['97']
    code:
      - 197003110 # 入院時食事療養（１）（１食につき）（流動食のみを提供）
  - key: shokuji-kijun-category-iv
    label: Ⅳ
    shinryou_shikibetsu: ['97']
    code:
      - 197003210 # 入院時食事療養（２）（１食につき）（流動食のみを提供）

  # 生活療養費 ローマ数字
  #
  # (22) 「食事・生活」欄について
  #
  # オ 「基準（生）」の項には、入院時生活療養費に係る生活療養について算定した項目を次の略号を用いて記載すること。ただし、複数の生活療養を算定し、「基準（生）」の項に複数の略号を記載することが困難な場合は、「摘要」欄への記載でも差し支えないこと。
  # Ⅰ（入院時生活療養Ⅰ(1)イ）、Ⅱ（入院時生活療養Ⅱ）、Ⅲ（入院時生活療養Ⅰ(1)ロ）

  - key: seikatsu-kijun-category-i
    label: Ⅰ
    shinryou_shikibetsu: ['97']
    code:
      - 197001310 # 入院時生活療養（１）食事療養（ロ以外の食事の提供たる療養）
  - key: seikatsu-kijun-category-ii
    label: Ⅱ
    shinryou_shikibetsu: ['97']
    code:
      - 197001710 # 入院時生活療養（２）食事療養
  - key: seikatsu-kijun-category-iii
    label: Ⅲ
    shinryou_shikibetsu: ['97']
    code:
      - 197003510 # 入院時生活療養（１）食事療養（流動食のみを提供）

  # 食事・生活療養費標準負担額

  - key: hyoujun-futangaku
    label: ~
    shinryou_shikibetsu: ['97']
    code:
      - 197000810 # 食事療養標準負担額（一般）
      - 197000910 # 食事療養標準負担額（低２・９０日以下）
      - 197001010 # 食事療養標準負担額（低２・９０日超）
      - 197001110 # 食事療養標準負担額（低１）
      - 197001210 # 食事療養標準負担額（他法等入院中）
      - 197001910 # 生活療養環境療養標準負担額
      - 197002010 # 生活療養（１）食事療養標準負担額（一般）
      - 197002110 # 生活療養（２）食事療養標準負担額（一般）
      - 197002210 # 生活療養食事療養標準負担額（低２）
      - 197002310 # 生活療養食事療養標準負担額（低１）
      - 197002510 # 生活療養食事療養標準負担額（後期高齢者低１（老福））
      - 197002810 # 生活療養食事療養標準負担額（医療区分２・３）（低２・９０日以下）
      - 197002910 # 生活療養食事療養標準負担額（医療区分２・３）（低２・９０日超）
      - 197003010 # 生活療養食事療養標準負担額（医療区分２・３）（低１）
      - 197003310 # 食事療養標準負担額（指定難病・小児慢性特定疾病患者）（一般）
      - 197003410 # 食事療養標準負担額（精神１年超）（一般）
      - 197003610 # 生活療養食事療養標準負担額（指定難病）（医療区分２・３）（一般）
      - 197003710 # 生活療養食事療養標準負担額（精神１年超・医療区分２・３）（一般）
      - 197003810 # 生活・環境負担額（医療区分２・３）
      - 197003910 # 生活・食事負担額（低）
      - 197004010 # 生活・食事負担額（境界層該当）（低）
      - 197004110 # 生活・食事負担額（境界層該当）（低１）
      - 197004210 # 生活・食事負担額（医療区分２・３）（低・９０日以下）
      - 197004310 # 生活・食事負担額（指定難病）（医療区分２・３）（低・９０日以下）
      - 197004410 # 生活・食事負担額（医療区分２・３）（低・９０日超）
      - 197004510 # 生活・食事負担額（指定難病）（医療区分２・３）（低・９０日超）
      - 197004610 # 生活・食事負担額（境界層該当）（医療区分２・３）（低）
      - 197004710 # 生活・食事負担額（指定難病・医療区分２・３）（低２・９０日以下）
      - 197004810 # 生活・食事負担額（指定難病）（医療区分２・３）（低２・９０日超）
      - 197004910 # 生活・食事負担額（指定難病）（医療区分２・３）（低１）
      - 197005010 # 生活・食事負担額（境界層該当）（医療区分２・３）（低１）
      - 197005110 # 生活療養（１）食事療養標準負担額（医療区分２・３）（一般）
      - 197005210 # 生活療養（２）食事療養標準負担額（医療区分２・３）（一般）

  # 病床区分
  #
  # 現状では療養病床のみ対応(回復期リハ病棟の療養病床も未対応)

  - key: byoushou-type-ryouyou # 「告示等識別区分（２）」が `1` かつ「コード表用番号（アルファベット部を除く）区分番号」が `101`
    label: 07療養
    shinryou_shikibetsu: ['90']
    code:
      - 190121810 # 療養病棟入院基本料（特別入院基本料）
      - 190124210 # 療養病棟入院基本料（特別入院基本料）（生活療養）
      - 190121310 # 療養病棟入院料１（入院料Ａ）
      - 190121410 # 療養病棟入院料１（入院料Ｂ）
      - 190121510 # 療養病棟入院料１（入院料Ｃ）
      - 190121610 # 療養病棟入院料１（入院料Ｄ）
      - 190121710 # 療養病棟入院料１（入院料Ｅ）
      - 190131610 # 療養病棟入院料１（入院料Ｆ）
      - 190131810 # 療養病棟入院料１（入院料Ｇ）
      - 190132010 # 療養病棟入院料１（入院料Ｈ）
      - 190132210 # 療養病棟入院料１（入院料Ｉ）
      - 190132410 # 療養病棟入院料２（入院料Ａ）
      - 190132610 # 療養病棟入院料２（入院料Ｂ）
      - 190132810 # 療養病棟入院料２（入院料Ｃ）
      - 190133010 # 療養病棟入院料２（入院料Ｄ）
      - 190133210 # 療養病棟入院料２（入院料Ｅ）
      - 190133410 # 療養病棟入院料２（入院料Ｆ）
      - 190133610 # 療養病棟入院料２（入院料Ｇ）
      - 190133810 # 療養病棟入院料２（入院料Ｈ）
      - 190134010 # 療養病棟入院料２（入院料Ｉ）
      - 190123710 # 療養病棟入院料１（入院料Ａ）（生活療養）
      - 190123810 # 療養病棟入院料１（入院料Ｂ）（生活療養）
      - 190123910 # 療養病棟入院料１（入院料Ｃ）（生活療養）
      - 190124010 # 療養病棟入院料１（入院料Ｄ）（生活療養）
      - 190124110 # 療養病棟入院料１（入院料Ｅ）（生活療養）
      - 190131710 # 療養病棟入院料１（入院料Ｆ）（生活療養）
      - 190131910 # 療養病棟入院料１（入院料Ｇ）（生活療養）
      - 190132110 # 療養病棟入院料１（入院料Ｈ）（生活療養）
      - 190132310 # 療養病棟入院料１（入院料Ｉ）（生活療養）
      - 190132510 # 療養病棟入院料２（入院料Ａ）（生活療養）
      - 190132710 # 療養病棟入院料２（入院料Ｂ）（生活療養）
      - 190132910 # 療養病棟入院料２（入院料Ｃ）（生活療養）
      - 190133110 # 療養病棟入院料２（入院料Ｄ）（生活療養）
      - 190133310 # 療養病棟入院料２（入院料Ｅ）（生活療養）
      - 190133510 # 療養病棟入院料２（入院料Ｆ）（生活療養）
      - 190133710 # 療養病棟入院料２（入院料Ｇ）（生活療養）
      - 190133910 # 療養病棟入院料２（入院料Ｈ）（生活療養）
      - 190134110 # 療養病棟入院料２（入院料Ｉ）（生活療養）
      - 190215210 # 療養病棟入院料２（Ａ）（生活療養）（経過措置）
      - 190215410 # 療養病棟入院料２（Ｂ）（生活療養）（経過措置）
      - 190215610 # 療養病棟入院料２（Ｃ）（生活療養）（経過措置）
      - 190215810 # 療養病棟入院料２（Ｄ）（生活療養）（経過措置）
      - 190216010 # 療養病棟入院料２（Ｅ）（生活療養）（経過措置）
      - 190216210 # 療養病棟入院料２（Ｆ）（生活療養）（経過措置）
      - 190216410 # 療養病棟入院料２（Ｇ）（生活療養）（経過措置）
      - 190216610 # 療養病棟入院料２（Ｈ）（生活療養）（経過措置）
      - 190216810 # 療養病棟入院料２（Ｉ）（生活療養）（経過措置）
      - 190215110 # 療養病棟入院料２（Ａ）（経過措置）
      - 190215310 # 療養病棟入院料２（Ｂ）（経過措置）
      - 190215510 # 療養病棟入院料２（Ｃ）（経過措置）
      - 190215710 # 療養病棟入院料２（Ｄ）（経過措置）
      - 190215910 # 療養病棟入院料２（Ｅ）（経過措置）
      - 190216110 # 療養病棟入院料２（Ｆ）（経過措置）
      - 190216310 # 療養病棟入院料２（Ｇ）（経過措置）
      - 190216510 # 療養病棟入院料２（Ｈ）（経過措置）
      - 190216710 # 療養病棟入院料２（Ｉ）（経過措置）
      - 190202410 # 療養病棟・地域一般入院料１
      - 190198310 # 療養病棟・地域一般入院料２
      - 190198410 # 療養病棟・地域一般入院料３
      - 190198110 # 療養病棟・急性期一般入院料１
      - 190201910 # 療養病棟・急性期一般入院料２
      - 190202010 # 療養病棟・急性期一般入院料３
      - 190202110 # 療養病棟・急性期一般入院料４
      - 190202210 # 療養病棟・急性期一般入院料５
      - 190198210 # 療養病棟・急性期一般入院料６
      - 190202310 # 療養病棟・急性期一般入院料６
      - 190198210 # 療養病棟・急性期一般入院料７
      - 190202310 # 療養病棟・急性期一般入院料６（経過措置）
